Repository bean3/to-do-list, pull requests merged in 2018-05, with the labels that each got.

#2 Issue #1 solved
  potato.py
Labels: enhancement

#11 mod 수정
  potato.py
Labels: CUI, basic function, bug

#18 Issue #8, 17 resolved
  potato.py
Labels: CUI, additional function, enhancement

#19 Issue #17 resolved
  data/category.py
  data/db.py
  data/detail.py
  data/find.py
  data/make.py
  data/modify.py
  data/page.py
  data/plan.py
  data/remove.py
  potato.py
Labels: CUI, additional function, basic function, enhancement

#21 Add Renew Fuction
  data/db.py
  data/make.py
  potato.py
Labels: additional function, enhancement

#26 Make setup.py
  setup.py
Labels: documentation

#27 First packaging
  potatodata/README.md
  potatodata/__init__.py
  potatodata/category.py
  potatodata/db.py
  potatodata/detail.py
  potatodata/find.py
  potatodata/make.py
  potatodata/modify.py
  potatodata/page.py
  potatodata/plan.py
  potatodata/potato.py
  potatodata/remove.py
  potatodata/setup.cfg
Labels: distribution, enhancement

#29 Ready for packaging this project
  README.md
  setup.cfg
  setup.py
Labels: distribution

#30 Directory fixed.
  potatodata/db.py
Labels: bug, enhancement

#32 Add an overdue status
  potatodata/db.py
  potatodata/plan.py
  potatodata/potato.py
  setup.py
Labels: additional function, enhancement
