Repository bean3/to-do-list, pull requests merged in 2018-06, with the labels that each got.

#34 Add a 'print version' option
  potatodata/plan.py
  potatodata/potato.py
  potatodata/version.py
Labels: additional function

#37 #22 resolved
  .gitignore
  potatodata/__init__ .py
  potatodata/plan.py
  potatodata/potato.py
Labels: enhancement

#40 #39 design and some bugs are fixed.
  potatodata/__init__.py
  potatodata/detail.py
  potatodata/plan.py
  potatodata/remove.py
  potatodata/version.py
  setup.py
Labels: bug

#42 #41 resolved
  potatodata/potato.py
Labels: CUI, enhancement

#46 resolved #45 : interactive mode added
  potatodata/category.py
  potatodata/db.py
  potatodata/find.py
  potatodata/make.py
  potatodata/modify.py
  potatodata/page.py
  potatodata/plan.py
  potatodata/potato.py
  potatodata/remove.py
  potatodata/version.py
  setup.py
Labels: CUI, additional function, basic function, enhancement

#48 #47 resolved
  potatodata/__init__.py
  potatodata/find.py
  potatodata/make.py
  potatodata/month.py
  potatodata/potato.py
  potatodata/remove.py
  potatodata/version.py
  setup.py
Labels: CUI, additional function

#51 Create .travis.yml
  .travis.yml
Labels: additional function, documentation

#56 #55 resolved
  .travis.yml
  README.md
  potatodata/db.py
  test.py
Labels: enhancement
